name: Generate Code

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download the Swagger file
        uses: wei/wget@v1
        with:
          args: -O .openapi-config/swagger.json https://api.ekm.net/swagger/v0/swagger.json

      - name: Replace the duplicate operationId
        run: sed -i '0,/"ProductVariants_Get"/{s/"ProductVariants_Get"/"ProductVariants_GetProductVariant"/}' .openapi-config/swagger.json

      - name: Remove existing client code
        run: rm -rf php-client

      - name: Update the version in the config
        run: sed -i "s/0.0.0/${TAG_VERSION/v/}/" .openapi-config/config.json
        env:
          TAG_VERSION: ${{ github.event.inputs.version }}

      - name: Generate Client Library w/ the OpenAPITools Generator
        uses: triaxtec/openapitools-generator-action@v1.1.1
        with:
          generator: php
          config-file: .openapi-config/config.json
          openapi-file: .openapi-config/swagger.json

      - name: Revert the version in the config
        run: sed -i "s/${TAG_VERSION/v/}/0.0.0/" .openapi-config/config.json
        env:
          TAG_VERSION: ${{ github.event.inputs.version }}

      - name: Replace tokens in files
        run: |
          sed -i 's/GIT_USER_ID/mrstebo/' php-client/composer.json
          sed -i 's/GIT_REPO_ID/ekm-php/' php-client/composer.json
          sed -i 's/GIT_USER_ID/mrstebo/' php-client/README.md
          sed -i 's/GIT_REPO_ID/ekm-php/' php-client/README.md

      - name: Update Guzzle package
        run: |
          sed -i 's/guzzle": "^6.2"/guzzle": "^7.0"/' php-client/composer.json

      - name: Copy files from php-client
        run: |
          for x in $(ls php-client -A); do
            rm -rf $x
            cp -rf php-client/$x $x
          done
          rm -rf php-client

      - name: Create commit
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v7
        with:
          message: "Build run #${{ github.run_number }}"
          push: true

      - name: Create commit and tag
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v7
        with:
          message: "Released version ${{ github.event.inputs.version }}"
          push: true
          tag: '${{ github.event.inputs.version }} --force'
