name: Generate Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download the Swagger file
        uses: wei/wget@v1
        with:
          args: -O .openapi-config/swagger.json https://api.ekm.net/swagger/v0/swagger.json
          
      - name: Replace the duplicate operationId
        run: sed -i 's/ProductVariants_Get/ProductVariants_GetProductVariant/' .openapi-config/swagger.json
      
      - name: Generate Client Library w/ the OpenAPITools Generator
        uses: triaxtec/openapitools-generator-action@v1.0.0
        with:
          generator: php
          config-file: .openapi-config/config.json
          openapi-file: .openapi-config/swagger.json
