name: Generate Code

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download the Swagger file
        uses: wei/wget@v1
        with:
          args: -O .openapi-config/swagger.json https://api.ekm.net/swagger/v0/swagger.json

      - name: Replace the duplicate operationId
        run: sed -i '0,/"ProductVariants_Get"/{s/"ProductVariants_Get"/"ProductVariants_GetProductVariant"/}' .openapi-config/swagger.json

      - name: Generate Client Library with the OpenAPITools Generator
        uses: addnab/docker-run-action@v3
        with:
          image: openapitools/openapi-generator-cli
          options: -v ${{ github.workspace }}:/local
          run: |
            generate \
              --input-spec /local/.openapi-config/swagger.json \
              --generator-name php \
              --config /local/.openapi-config/config.json \
              --git-repo-id ekm-php \
              --git-user-id mrstebo \
              --output /local \
              --verbose

      - uses: EndBug/add-and-commit@v7
        with:
          message: ${{ github.event.inputs.message }}
          push: true
          tag: '${{ github.event.inputs.version }} --force'
